simulation:
  threeDimensions: true
  size:
    width: 500
    height: 500
    depth: 50
  count: 10000
  dT: "0.001"
  maxForce: "50000.0"
  maxVelocity: "20.0"
  epsilon: 100
interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: "8.0"
      epsilon: "1.0"
  hydrogen-hydrogen:
    lennardJones:
      sigma: "23.0"
      epsilon: "57.0"
  oxygen-oxygen:
    lennardJones:
      sigma: "81.0"
      epsilon: "44.0"
