simulation:
  count: 10000
  minGridSize: 5.0
  epsilon: 100.0
  dT: 0.001
  maxVelocity: 4.311595
  maxForce: 50000.0
  threeDimensions: true
  passesPerFrame: 100
  size:
    width: 500
    height: 500
    depth: 100
interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: 6.245179
      epsilon: 200.0
  hydrogen-hydrogen:
    lennardJones:
      sigma: 5.767499
      epsilon: 0.0
  oxygen-oxygen:
    lennardJones:
      sigma: 8.46739
      epsilon: 3.9855075
