simulation:
  count: 10000
  minGridSize: 5.0
  dT: 0.005
  maxVelocity: 4.0
  maxForce: 50000.0
  threeDimensions: true
  passesPerFrame: 100
  size:
    width: 500
    height: 500
    depth: 500
interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: 3.0
      epsilon: 200.0
  hydrogen-hydrogen:
    lennardJones:
      sigma: 2.0
      epsilon: 5.0
  oxygen-oxygen:
    lennardJones:
      sigma: 5.0
      epsilon: 2.0
