#version 430
layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

uniform int numValues;

layout (binding = 0) buffer keysBuffer {
    uint keys[];
};

layout (binding = 1) buffer offsetsBuffer {
    uint offsets[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= numValues) return;

    uint null = numValues;

    uint key = keys[id];
    uint keyPrev = id == 0 ? null : keys[id - 1];

    if (key != keyPrev) offsets[key] = id;
}
