interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: 5.0
      epsilon: 5.0
  hydrogen-hydrogen:
    lennardJones:
      sigma: 5.0
      epsilon: 5.0
  oxygen-oxygen:
    lennardJones:
      sigma: 10.0
      epsilon: 5.0
