simulation:
  count: 5144
  minGridSize: 5.0
  dT: 0.001
  maxVelocity: 4.0
  maxForce: 50000.0
  threeDimensions: false
  passesPerFrame: 100
  size:
    width: 500
    height: 500
    depth: 500
interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: 5.0
      epsilon: 5.0
  hydrogen-hydrogen:
    lennardJones:
      sigma: 5.0
      epsilon: 5.0
  oxygen-oxygen:
    lennardJones:
      sigma: 10.0
      epsilon: 5.0
