interactions:
  hydrogen-oxygen:
    lennardJones:
      sigma: 2.54
      epsilon: 123.68
  hydrogen-hydrogen:
    lennardJones:
      sigma: 2.64
      epsilon: 5.0
  oxygen-oxygen:
    lennardJones:
      sigma: 3.35
      epsilon: 50.86
